spring.application.name=ms-string-provider
server.port=8082
spring.profiles.active=prod
spring.config.import=optional:configserver:http://localhost:8888
# Configure the application.properties to expose the /actuator/refresh endpoint:
#management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=refresh
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#STRING TRANSFORMER
ms-string-transformer.url=http://localhost:8083
